//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impl.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTap
    {
        public int id { get; set; }
        public long idDevice { get; set; }
        public Nullable<int> idDrink { get; set; }
        public int TapCode { get; set; }
        public Nullable<int> idFutureDrink { get; set; }
        public Nullable<System.DateTimeOffset> FutureDrinkDate { get; set; }
    }
}
