//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impl.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int id { get; set; }
        public int idDrink { get; set; }
        public int Val { get; set; }
        public System.DateTimeOffset StartTs { get; set; }
        public Nullable<System.DateTimeOffset> EndTs { get; set; }
        public Nullable<int> idMarket { get; set; }
    }
}
