//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impl.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public int idUser { get; set; }
        public string Kpp { get; set; }
        public string Ogrn { get; set; }
        public string Account { get; set; }
        public string Bik { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTimeOffset> ActualDate { get; set; }
        public string ActualAddress { get; set; }
    }
}
