//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impl.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public long id { get; set; }
        public int idMarket { get; set; }
        public Nullable<int> idDrink { get; set; }
        public long idFill { get; set; }
        public int idPrice { get; set; }
        public int Volume { get; set; }
        public int Sum { get; set; }
        public bool isCleaning { get; set; }
        public System.DateTimeOffset Ts { get; set; }
    }
}
