//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impl.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public long id { get; set; }
        public int idMarket { get; set; }
        public Nullable<int> idDrink { get; set; }
        public long idFill { get; set; }
        public int idPrice { get; set; }
        public int Volume { get; set; }
        public int Sum { get; set; }
        public bool isCleaning { get; set; }
        public System.DateTimeOffset Ts { get; set; }
    }
}
